# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_discussiontopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOfTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DiscussionTopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo')),
            ],
        ),
    ]
