# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_commentoftopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentoftopic',
            name='commentText',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='commentoftopic',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
