# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160323_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentoftopic',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 8, 2, 8, 309569, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
