# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160323_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentoftopic',
            old_name='timestamp',
            new_name='timeStamp',
        ),
    ]
